name: 🚀 Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

      - name: 🚀 Deploy ke EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          
          cd ~/Uts-cloud-reynal-sampah
          
          git pull origin main
          
          sudo docker-compose down
          sudo docker-compose up -d --build
          
          sudo docker exec sampahrey-app php artisan migrate --force
          
          EOF
